apiVersion: v1
kind: Service
metadata:
  name: autocomplete-service
spec:
  selector:
    app: autocomplete-service
  ports:
    - protocol: TCP
      port: 80  # External port to access the service
      targetPort: 2345  # Port on the container
  type: LoadBalancer
